### ISSUE TITLE
Icon Request: Visual Studio Code

### ISSUE THREAD

**Issue by fusion809** [trenta-io/rainierUI-icons#4]
Hi,

I would like to request an icon for Visual Studio Code (icon name: `code`, `code-oss` and `visual-studio-code`). 

Thanks for your time,
Brenton

**Comment by KevDoy** [comment]
Added: a727bade69d4217e9a34811c3731aa51ae5860b5

**Comment by fusion809** [comment]
Thanks, closing.

**Comment by KevDoy** [comment]
Thank you for submitting such a clear request. We'll add the links you requested during the next push.
